# Generated by Django 2.0.2 on 2018-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebudget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='dayOfTheWeek',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='startTime',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_of_the_week',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='SUN', max_length=3),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.DurationField(),
        ),
    ]
