# Generated by Django 2.0.2 on 2018-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebudget', '0004_auto_20180311_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day_of_the_week',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(default='09:00:00'),
        ),
    ]
